# Generated by Django 5.1.2 on 2024-10-19 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_rename_location_facility_city_facility_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
