# Generated by Django 5.1.3 on 2024-11-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_alter_facility_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
