# Generated by Django 5.1.1 on 2024-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
