# Generated by Django 5.1.3 on 2024-11-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounddetails',
            name='product_id',
            field=models.CharField(default=1, editable=False, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilityinventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inbounddetails',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='pack_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='warehouseinventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
