# Generated by Django 5.1.3 on 2024-11-12 20:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0005_alter_facility_options_facility_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=6, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('member_type', models.CharField(choices=[('member', 'Member'), ('insurance', 'Insurance Member'), ('corporate', 'Corporate Member')])),
                ('insurance_id', models.CharField()),
                ('insurance_company', models.CharField(blank=True, choices=[('acacia', 'Acacia Health Insurance'), ('apex', 'Apex Health Insurance'), ('glico_health', 'Glico Health Insurane'), ('glico_tpa', 'Glico TPA')])),
                ('corporate_id', models.CharField()),
                ('corporate_company', models.CharField(blank=True, choices=[('vivo', 'Vivo Energy Limited'), ('mtn', 'MTN Ghana'), ('stanbic_bank', 'Stanbic Bank Ghana')])),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('parent_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='facilities.facility')),
            ],
        ),
    ]
